# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"conserved_areas_for_year_natura": "00_landcover_pct.ipynb",
         "conserved_areas_for_year_cdda": "00_landcover_pct.ipynb"}

modules = ["landcover.py"]

doc_url = "https://jaeeolma.github.io/luonnontilafi/"

git_url = "https://github.com/jaeeolma/luonnontilafi/tree/main/"

def custom_doc_links(name): return None
